import 'dart:convert';
import 'package:flutter/material.dart';
import 'package:http/http.dart' as http;
import 'package:shared_preferences/shared_preferences.dart';

const apiBaseUrl = String.fromEnvironment('API_BASE_URL', defaultValue: 'http://10.0.2.2:4000/api');
const savedCustomerPhoneKey = 'customer_phone';
String normalizePhone(String value) => value.trim().replaceAll(RegExp(r'\s+'), '');

void main() => runApp(const BeautyHomeServiceApp());

class BeautyHomeServiceApp extends StatelessWidget {
  const BeautyHomeServiceApp({super.key});
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'Beauty Home Service',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: const Color(0xFF8B5A2B)),
        useMaterial3: true,
        filledButtonTheme: FilledButtonThemeData(style: FilledButton.styleFrom(backgroundColor: const Color(0xFF6B3F19), foregroundColor: Colors.white, padding: const EdgeInsets.symmetric(vertical: 14))),
      ),
      home: const Directionality(textDirection: TextDirection.rtl, child: HomeScreen()),
    );
  }
}

class ApiClient {
  static Uri uri(String path) {
    final base = apiBaseUrl.endsWith('/') ? apiBaseUrl.substring(0, apiBaseUrl.length - 1) : apiBaseUrl;
    final cleanPath = path.startsWith('/') ? path : '/$path';
    return Uri.parse('$base$cleanPath');
  }
  static Future<dynamic> get(String path) async => _parse(await http.get(uri(path)));
  static Future<dynamic> post(String path, Map<String, dynamic> body) async => _parse(await http.post(uri(path), headers: {'Content-Type': 'application/json; charset=utf-8'}, body: jsonEncode(body)));
  static dynamic _parse(http.Response response) {
    final text = utf8.decode(response.bodyBytes).trim();
    dynamic data;
    try { data = text.isEmpty ? null : jsonDecode(text); }
    catch (_) { final shortText = text.length > 180 ? '${text.substring(0, 180)}...' : text; throw Exception('استجابة غير صالحة من السيرفر (${response.statusCode}): $shortText'); }
    if (response.statusCode < 200 || response.statusCode >= 300) {
      final message = data is Map ? (data['error'] ?? data['details'] ?? 'حدث خطأ') : 'حدث خطأ';
      throw Exception(message);
    }
    return data;
  }
}

InputDecoration inputDecoration(String label) => InputDecoration(labelText: label, filled: true, fillColor: Colors.white, border: OutlineInputBorder(borderRadius: BorderRadius.circular(16)));
String requiredValidator(String? v) => (v == null || v.trim().isEmpty) ? 'مطلوب' : '';
String dateOnly(dynamic v) => v == null ? '-' : DateTime.tryParse(v.toString())?.toString().substring(0, 10) ?? v.toString();
String timeOnly(dynamic v) { final text = v?.toString() ?? ''; return text.isEmpty ? '-' : (text.length >= 5 ? text.substring(0,5) : text); }
String nameOf(dynamic item) => (item is Map ? (item['name_ar'] ?? item['display_name'] ?? item['name'] ?? '-') : '-').toString();
List safeList(dynamic data) => data is List ? data : [];

class HomeScreen extends StatefulWidget { const HomeScreen({super.key}); @override State<HomeScreen> createState() => _HomeScreenState(); }
class _HomeScreenState extends State<HomeScreen> {
  final phoneController = TextEditingController();
  @override void initState() { super.initState(); loadSavedPhone(); }
  Future<void> loadSavedPhone() async { final prefs = await SharedPreferences.getInstance(); final saved = prefs.getString(savedCustomerPhoneKey); if (saved != null && mounted) phoneController.text = saved; }
  @override void dispose() { phoneController.dispose(); super.dispose(); }
  @override Widget build(BuildContext context) => Scaffold(
    backgroundColor: const Color(0xFFFBF4EA),
    appBar: AppBar(title: const Text('Beauty Home Service'), centerTitle: true),
    body: ListView(padding: const EdgeInsets.all(20), children: [
      Container(padding: const EdgeInsets.all(24), decoration: BoxDecoration(borderRadius: BorderRadius.circular(28), gradient: const LinearGradient(colors:[Color(0xFF6B3F19), Color(0xFFB88943)])), child: const Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text('خدمات تجميل منزلية بسهولة', style: TextStyle(color: Colors.white, fontSize: 25, fontWeight: FontWeight.bold)), SizedBox(height:8), Text('اختاري الخدمة، شاهدي نماذج أعمال الخبيرات، ثم ارسلي طلبك.', style: TextStyle(color: Colors.white, fontSize: 15))])),
      const SizedBox(height:20),
      TextField(controller: phoneController, keyboardType: TextInputType.phone, decoration: inputDecoration('رقم الجوال لمتابعة الطلبات')),
      const SizedBox(height:12), FilledButton(onPressed:()=>Navigator.push(context, MaterialPageRoute(builder:(_)=>const BookingScreen())), child: const Text('احجزي الآن', style: TextStyle(fontSize:18))),
      const SizedBox(height:10), OutlinedButton(onPressed:()=>Navigator.push(context, MaterialPageRoute(builder: (_) => MyBookingsScreen(phone: normalizePhone(phoneController.text)))), child: const Text('طلباتي')),
      const SizedBox(height:10), OutlinedButton(onPressed:()=>Navigator.push(context, MaterialPageRoute(builder: (_) => const BeauticiansScreen())), child: const Text('تصفحي خبيرات التجميل ونماذج الأعمال')),
      const SizedBox(height:14), const Text('v1.6: معرض أعمال الخبيرات، اختيار خبيرة مفضلة، وتقييم بعد تنفيذ الطلب.', textAlign: TextAlign.center),
    ])
  );
}

class BookingScreen extends StatefulWidget { const BookingScreen({super.key}); @override State<BookingScreen> createState()=>_BookingScreenState(); }
class _BookingScreenState extends State<BookingScreen> {
  final formKey = GlobalKey<FormState>();
  final name = TextEditingController(); final phone = TextEditingController(); final eventType = TextEditingController(text:'زواج'); final people = TextEditingController(text:'1'); final address = TextEditingController(); final notes = TextEditingController(); final designImageUrl = TextEditingController();
  DateTime? bookingDate; TimeOfDay? bookingTime; bool loading = true; bool saving = false; String? error;
  List regions=[]; List cities=[]; List districts=[]; List categories=[]; List services=[]; List beauticians=[]; List portfolio=[];
  String? selectedRegionId; String? selectedCityId; String? selectedDistrictId; String? selectedCategoryId; String? selectedServiceId; String? preferredBeauticianId;
  @override void initState(){ super.initState(); loadSavedPhone(); loadInitialLists(); }
  Future<void> loadSavedPhone() async { final prefs=await SharedPreferences.getInstance(); final saved=prefs.getString(savedCustomerPhoneKey); if(saved!=null&&mounted) phone.text=saved; }
  @override void dispose(){ name.dispose();phone.dispose();eventType.dispose();people.dispose();address.dispose();notes.dispose();designImageUrl.dispose();super.dispose(); }
  Future<void> loadInitialLists() async { setState(() => loading = true); try { final results = await Future.wait([ApiClient.get('/regions'), ApiClient.get('/service-categories')]); regions = safeList(results[0]); categories = safeList(results[1]); } catch (e) { error = e.toString(); } finally { if (mounted) setState(() => loading = false); } }
  Future<void> loadCities(String? regionId) async { selectedRegionId = regionId; selectedCityId = null; selectedDistrictId = null; preferredBeauticianId = null; cities = []; districts = []; beauticians=[]; portfolio=[]; if (regionId==null||regionId.isEmpty) { setState((){}); return; } setState(()=>loading=true); try { cities = safeList(await ApiClient.get('/cities?region_id=$regionId')); } catch(e){ error=e.toString(); } finally { if(mounted) setState(()=>loading=false); } }
  Future<void> loadDistricts(String? cityId) async { selectedCityId=cityId; selectedDistrictId=null; preferredBeauticianId=null; districts=[]; beauticians=[]; portfolio=[]; if(cityId==null||cityId.isEmpty){setState((){});return;} setState(()=>loading=true); try{ districts=safeList(await ApiClient.get('/districts?city_id=$cityId')); await loadBeauticians(); }catch(e){error=e.toString();}finally{if(mounted)setState(()=>loading=false);} }
  Future<void> loadServices(String? categoryId) async { selectedCategoryId=categoryId; selectedServiceId=null; preferredBeauticianId=null; services=[]; beauticians=[]; portfolio=[]; if(categoryId==null||categoryId.isEmpty){setState((){});return;} setState(()=>loading=true); try{ services=safeList(await ApiClient.get('/services?category_id=$categoryId')); }catch(e){error=e.toString();}finally{if(mounted)setState(()=>loading=false);} }
  Future<void> selectService(String? serviceId) async { selectedServiceId=serviceId; preferredBeauticianId=null; await loadBeauticians(); }
  Future<void> loadBeauticians() async { if(selectedServiceId==null||selectedServiceId!.isEmpty){setState((){});return;} final qs=['service_id=$selectedServiceId']; if(selectedRegionId!=null) qs.add('region_id=$selectedRegionId'); if(selectedCityId!=null) qs.add('city_id=$selectedCityId'); beauticians=safeList(await ApiClient.get('/beauticians?${qs.join('&')}')); portfolio=safeList(await ApiClient.get('/portfolio?service_id=$selectedServiceId')); if(mounted)setState((){}); }
  String dateText()=> bookingDate==null ? 'اختيار التاريخ' : '${bookingDate!.year}-${bookingDate!.month.toString().padLeft(2,'0')}-${bookingDate!.day.toString().padLeft(2,'0')}';
  String timeText()=> bookingTime==null ? 'اختيار الوقت' : '${bookingTime!.hour.toString().padLeft(2,'0')}:${bookingTime!.minute.toString().padLeft(2,'0')}';
  Future<void> submit() async { if(!formKey.currentState!.validate()) return; if(bookingDate==null||bookingTime==null){ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('اختر التاريخ والوقت')));return;} if([selectedRegionId,selectedCityId,selectedDistrictId,selectedCategoryId,selectedServiceId].any((e)=>e==null||e.toString().isEmpty)){ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('أكمل اختيار الموقع والخدمة')));return;} setState(()=>saving=true); try{final customerPhone=normalizePhone(phone.text); final created=await ApiClient.post('/bookings', {'name':name.text.trim(),'phone':customerPhone,'region_id':selectedRegionId,'city_id':selectedCityId,'district_id':selectedDistrictId,'service_category_id':selectedCategoryId,'event_type':eventType.text.trim(),'service_id':selectedServiceId,'preferred_artist_id':preferredBeauticianId,'booking_date':dateText(),'booking_time':timeText(),'people_count':int.tryParse(people.text.trim())??1,'address':address.text.trim(),'design_image_url':designImageUrl.text.trim().isEmpty?null:designImageUrl.text.trim(),'customer_notes':notes.text.trim()}); final prefs=await SharedPreferences.getInstance(); await prefs.setString(savedCustomerPhoneKey, customerPhone); if(!mounted)return; Navigator.pushReplacement(context, MaterialPageRoute(builder:(_)=>BookingSubmittedScreen(bookingId:created['id']?.toString(), phone:customerPhone)));}catch(e){ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text('تعذر إرسال الطلب: $e')));}finally{if(mounted)setState(()=>saving=false);} }
  @override Widget build(BuildContext context)=>Scaffold(backgroundColor:const Color(0xFFFBF4EA), appBar:AppBar(title:const Text('طلب حجز Beauty Home Service')), body: loading?const Center(child:CircularProgressIndicator()):Form(key:formKey, child:ListView(padding:const EdgeInsets.all(18), children:[
    if(error!=null) Text('تنبيه: $error', style:TextStyle(color:Colors.orange.shade900)),
    TextFormField(controller:name, decoration:inputDecoration('اسم العميلة'), validator:(v)=>requiredValidator(v).isEmpty?null:requiredValidator(v)), const SizedBox(height:12),
    TextFormField(controller:phone, keyboardType:TextInputType.phone, decoration:inputDecoration('رقم الجوال'), validator:(v)=>requiredValidator(v).isEmpty?null:requiredValidator(v)), const SizedBox(height:12),
    dropdown('المنطقة', selectedRegionId, regions, loadCities), const SizedBox(height:12), dropdown('المدينة', selectedCityId, cities, loadDistricts), const SizedBox(height:12), dropdown('الحي', selectedDistrictId, districts, (v)=>setState(()=>selectedDistrictId=v)), const SizedBox(height:12),
    TextFormField(controller:eventType, decoration:inputDecoration('نوع المناسبة'), validator:(v)=>requiredValidator(v).isEmpty?null:requiredValidator(v)), const SizedBox(height:12), dropdown('قسم الخدمة', selectedCategoryId, categories, loadServices), const SizedBox(height:12), dropdown('الخدمة', selectedServiceId, services, selectService), const SizedBox(height:12),
    if(portfolio.isNotEmpty) PortfolioStrip(items: portfolio, onTapBeautician: (id){ setState(()=>preferredBeauticianId=id); }),
    if(beauticians.isNotEmpty) DropdownButtonFormField<String>(value: preferredBeauticianId ?? '', decoration:inputDecoration('خبيرة مفضلة - اختياري'), items:[const DropdownMenuItem<String>(value:'', child:Text('اتركي الاختيار للدعم')), ...beauticians.map<DropdownMenuItem<String>>((a)=>DropdownMenuItem(value:a['id']?.toString(), child:Text('${a['name']} • ${a['review_rating'] ?? a['rating'] ?? '-'}★')))], onChanged:(v)=>setState(()=>preferredBeauticianId=(v==null||v.isEmpty)?null:v)),
    const SizedBox(height:12), Row(children:[Expanded(child:OutlinedButton(onPressed:()async{final d=await showDatePicker(context:context, firstDate:DateTime.now(), lastDate:DateTime.now().add(const Duration(days:365)), initialDate:DateTime.now()); if(d!=null)setState(()=>bookingDate=d);}, child:Text(dateText()))), const SizedBox(width:10), Expanded(child:OutlinedButton(onPressed:()async{final t=await showTimePicker(context:context, initialTime:const TimeOfDay(hour:18,minute:0)); if(t!=null)setState(()=>bookingTime=t);}, child:Text(timeText()))) ]), const SizedBox(height:12),
    TextFormField(controller:people, keyboardType:TextInputType.number, decoration:inputDecoration('عدد الأشخاص')), const SizedBox(height:12), TextFormField(controller:address, decoration:inputDecoration('العنوان'), validator:(v)=>requiredValidator(v).isEmpty?null:requiredValidator(v)), const SizedBox(height:12), TextFormField(controller:designImageUrl, decoration:inputDecoration('رابط صورة التصميم - اختياري')), const SizedBox(height:12), TextFormField(controller:notes, minLines:2, maxLines:4, decoration:inputDecoration('ملاحظات')), const SizedBox(height:20), FilledButton(onPressed:saving?null:submit, child:Text(saving?'جاري الإرسال...':'إرسال الطلب'))
  ])));
  Widget dropdown(String label, String? value, List items, Function(String?) onChanged) => DropdownButtonFormField<String>(value:(value!=null && items.any((i)=>i['id']?.toString()==value))?value:null, decoration:inputDecoration(label), items:items.map<DropdownMenuItem<String>>((i)=>DropdownMenuItem(value:i['id']?.toString(), child:Text(nameOf(i)))).toList(), onChanged:onChanged, validator:(v)=>(v==null||v.isEmpty)?'مطلوب':null);
}

class PortfolioStrip extends StatelessWidget { final List items; final void Function(String?)? onTapBeautician; const PortfolioStrip({super.key, required this.items, this.onTapBeautician}); @override Widget build(BuildContext context)=>Column(crossAxisAlignment:CrossAxisAlignment.start, children:[const Text('نماذج أعمال مشابهة', style:TextStyle(fontSize:18,fontWeight:FontWeight.bold)), const SizedBox(height:8), SizedBox(height:210, child:ListView.separated(scrollDirection:Axis.horizontal, itemCount:items.length, separatorBuilder:(_,__)=>const SizedBox(width:10), itemBuilder:(context,i){ final p=items[i]; return InkWell(onTap:()=>onTapBeautician?.call(p['beautician_id']?.toString()), child:Container(width:180, decoration:BoxDecoration(color:Colors.white,borderRadius:BorderRadius.circular(18), border:Border.all(color:const Color(0xFFE8D6C3))), padding:const EdgeInsets.all(8), child:Column(crossAxisAlignment:CrossAxisAlignment.start, children:[ClipRRect(borderRadius:BorderRadius.circular(14), child:Image.network(p['image_url']??'', height:115, width:164, fit:BoxFit.cover, errorBuilder:(_,__,___)=>Container(height:115,color:const Color(0xFFF2E6D9),child:const Icon(Icons.image)))), const SizedBox(height:8), Text(p['title_ar']??'-', maxLines:1, overflow:TextOverflow.ellipsis, style:const TextStyle(fontWeight:FontWeight.bold)), Text(p['beautician_name']??'-', maxLines:1, overflow:TextOverflow.ellipsis), Text(p['service_name']??'', maxLines:1, overflow:TextOverflow.ellipsis, style:const TextStyle(fontSize:12,color:Colors.brown))]))); }))]); }

class BeauticiansScreen extends StatefulWidget { const BeauticiansScreen({super.key}); @override State<BeauticiansScreen> createState()=>_BeauticiansScreenState(); }
class _BeauticiansScreenState extends State<BeauticiansScreen> { bool loading=true; String? error; List beauticians=[]; @override void initState(){super.initState();load();} Future<void> load() async{setState(()=>loading=true);try{beauticians=safeList(await ApiClient.get('/beauticians'));}catch(e){error=e.toString();}finally{if(mounted)setState(()=>loading=false);}} @override Widget build(BuildContext context)=>Scaffold(backgroundColor:const Color(0xFFFBF4EA), appBar:AppBar(title:const Text('خبيرات التجميل')), body:loading?const Center(child:CircularProgressIndicator()):ListView(padding:const EdgeInsets.all(16), children:[if(error!=null)Text(error!,style:const TextStyle(color:Colors.red)), ...beauticians.map((a)=>Card(child:ListTile(leading:CircleAvatar(backgroundImage:(a['featured_image_url']??a['first_image_url'])!=null?NetworkImage(a['featured_image_url']??a['first_image_url']):null, child:(a['featured_image_url']??a['first_image_url'])==null?const Icon(Icons.person):null), title:Text(a['name']??'-'), subtitle:Text('${a['main_expertise_name']??'-'} • ${a['city_name']??'-'} • ${a['review_rating']??a['rating']??'-'}★'), trailing:const Icon(Icons.chevron_left), onTap:()=>Navigator.push(context, MaterialPageRoute(builder:(_)=>BeauticianDetailsScreen(id:a['id'].toString()))))))])); }
class BeauticianDetailsScreen extends StatefulWidget { final String id; const BeauticianDetailsScreen({super.key, required this.id}); @override State<BeauticianDetailsScreen> createState()=>_BeauticianDetailsScreenState(); }
class _BeauticianDetailsScreenState extends State<BeauticianDetailsScreen> { bool loading=true; dynamic data; String? error; @override void initState(){super.initState();load();} Future<void> load() async{try{data=await ApiClient.get('/beauticians/${widget.id}');}catch(e){error=e.toString();}finally{if(mounted)setState(()=>loading=false);}} @override Widget build(BuildContext context){ if(loading)return const Scaffold(body:Center(child:CircularProgressIndicator())); final b=data?['beautician']??{}; final p=safeList(data?['portfolio']); final r=safeList(data?['reviews']); return Scaffold(backgroundColor:const Color(0xFFFBF4EA), appBar:AppBar(title:Text(b['name']??'خبيرة التجميل')), body:ListView(padding:const EdgeInsets.all(16), children:[if(error!=null)Text(error!,style:const TextStyle(color:Colors.red)), Card(child:Padding(padding:const EdgeInsets.all(16),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(b['name']??'-',style:const TextStyle(fontSize:24,fontWeight:FontWeight.bold)), Text('${b['main_expertise_name']??'-'} • ${b['city_name']??'-'}'), Text('التقييم: ${b['review_rating']??b['rating']??'-'} ★ (${b['review_count']??0})'), if((b['bio']??'').toString().isNotEmpty) Padding(padding:const EdgeInsets.only(top:8),child:Text(b['bio']))]))), PortfolioStrip(items:p), const SizedBox(height:12), const Text('التقييمات', style:TextStyle(fontSize:18,fontWeight:FontWeight.bold)), ...r.map((x)=>Card(child:ListTile(title:Text('${x['rating']} ★'), subtitle:Text(x['review_text']??''))))])); }}

class BookingSubmittedScreen extends StatelessWidget { final String? bookingId; final String phone; const BookingSubmittedScreen({super.key, this.bookingId, required this.phone}); @override Widget build(BuildContext context)=>Scaffold(backgroundColor:const Color(0xFFFBF4EA), appBar:AppBar(title:const Text('تم إرسال الطلب')), body:Padding(padding:const EdgeInsets.all(20), child:Column(mainAxisAlignment:MainAxisAlignment.center, crossAxisAlignment:CrossAxisAlignment.stretch, children:[const Icon(Icons.check_circle, size:90, color:Color(0xFF6B3F19)), const SizedBox(height:20), const Text('تم إرسال طلبك بنجاح', textAlign:TextAlign.center, style:TextStyle(fontSize:24,fontWeight:FontWeight.bold)), const SizedBox(height:12), Text('رقم الطلب: ${bookingId ?? '-'}', textAlign:TextAlign.center), const SizedBox(height:30), FilledButton(onPressed:()=>Navigator.pushReplacement(context, MaterialPageRoute(builder:(_)=>MyBookingsScreen(phone:phone))), child:const Text('متابعة طلباتي')), const SizedBox(height:10), OutlinedButton(onPressed:()=>Navigator.popUntil(context,(r)=>r.isFirst), child:const Text('الرئيسية'))]))); }
class MyBookingsScreen extends StatefulWidget { final String phone; const MyBookingsScreen({super.key, required this.phone}); @override State<MyBookingsScreen> createState()=>_MyBookingsScreenState(); }
class _MyBookingsScreenState extends State<MyBookingsScreen> { final phoneController=TextEditingController(); bool loading=false; String? error; List bookings=[]; @override void initState(){ super.initState(); phoneController.text=widget.phone; loadInitial(); } Future<void> loadInitial() async { if(phoneController.text.trim().isEmpty){ final prefs=await SharedPreferences.getInstance(); phoneController.text=prefs.getString(savedCustomerPhoneKey)??''; } if(phoneController.text.trim().isNotEmpty) load(); } Future<void> load() async { final phone=normalizePhone(phoneController.text); if(phone.isEmpty){ setState(()=>error='أدخل رقم الجوال'); return; } setState((){loading=true;error=null;}); try{ final data=await ApiClient.get('/customer/bookings?phone=$phone'); final prefs=await SharedPreferences.getInstance(); await prefs.setString(savedCustomerPhoneKey, phone); bookings=safeList(data); }catch(e){error=e.toString();}finally{if(mounted)setState(()=>loading=false);} } @override void dispose(){phoneController.dispose();super.dispose();} @override Widget build(BuildContext context)=>Scaffold(backgroundColor:const Color(0xFFFBF4EA), appBar:AppBar(title:const Text('طلباتي')), body:ListView(padding:const EdgeInsets.all(18), children:[TextField(controller:phoneController, keyboardType:TextInputType.phone, decoration:inputDecoration('رقم الجوال')), const SizedBox(height:10), FilledButton(onPressed:load, child:const Text('بحث')), if(error!=null) Padding(padding:const EdgeInsets.all(10), child:Text(error!, style:const TextStyle(color:Colors.red))), if(loading) const Center(child:CircularProgressIndicator()), if(!loading&&bookings.isEmpty) const Padding(padding:EdgeInsets.all(25), child:Text('لا توجد طلبات', textAlign:TextAlign.center)), ...bookings.map((b)=>BookingCard(booking:b, onReload:load))])); }
class BookingCard extends StatelessWidget { final dynamic booking; final VoidCallback onReload; const BookingCard({super.key, required this.booking, required this.onReload}); @override Widget build(BuildContext context){ final status=booking['status']; return Card(margin:const EdgeInsets.only(bottom:12), child:Padding(padding:const EdgeInsets.all(12), child:Column(crossAxisAlignment:CrossAxisAlignment.start, children:[Text('${booking['service_category_name'] ?? '-'} / ${booking['service_name'] ?? '-'}', style:const TextStyle(fontWeight:FontWeight.bold,fontSize:16)), const SizedBox(height:6), Text('${booking['region_name'] ?? '-'} • ${booking['city_name'] ?? '-'} • ${booking['district_name'] ?? '-'}'), if(booking['preferred_artist_name']!=null) Text('الخبيرة المفضلة: ${booking['preferred_artist_name']}'), if(booking['artist_name']!=null) Text('الخبيرة المعينة: ${booking['artist_name']}'), Text('${dateOnly(booking['booking_date'])} • ${timeOnly(booking['booking_time'])}'), const SizedBox(height:8), Text('الحالة: ${statusArabic(status)}'), const SizedBox(height:8), TimelineStatus(current: status?.toString() ?? 'new'), if(status=='completed' && booking['customer_review_rating']==null) Align(alignment:Alignment.centerLeft, child:OutlinedButton(onPressed:()=>showDialog(context:context,builder:(_)=>ReviewDialog(bookingId:booking['id'], onSaved:onReload)), child:const Text('تقييم الخبيرة')))]))) ; } }
class ReviewDialog extends StatefulWidget { final String bookingId; final VoidCallback onSaved; const ReviewDialog({super.key, required this.bookingId, required this.onSaved}); @override State<ReviewDialog> createState()=>_ReviewDialogState(); }
class _ReviewDialogState extends State<ReviewDialog> { int rating=5; final note=TextEditingController(); bool saving=false; @override Widget build(BuildContext context)=>AlertDialog(title:const Text('تقييم الخبيرة'), content:Column(mainAxisSize:MainAxisSize.min,children:[DropdownButtonFormField<int>(value:rating, decoration:inputDecoration('التقييم'), items:[1,2,3,4,5].map((x)=>DropdownMenuItem(value:x,child:Text('$x نجوم'))).toList(), onChanged:(v)=>setState(()=>rating=v??5)), const SizedBox(height:10), TextField(controller:note, decoration:inputDecoration('تعليق اختياري'), maxLines:3)]), actions:[TextButton(onPressed:()=>Navigator.pop(context), child:const Text('إلغاء')), FilledButton(onPressed:saving?null:()async{setState(()=>saving=true); try{await ApiClient.post('/customer/reviews', {'booking_id':widget.bookingId,'rating':rating,'review_text':note.text.trim()}); if(context.mounted){Navigator.pop(context); widget.onSaved();}}finally{if(mounted)setState(()=>saving=false);}}, child:const Text('حفظ'))]); }
class TimelineStatus extends StatelessWidget { final String current; const TimelineStatus({super.key, required this.current}); @override Widget build(BuildContext context){ final steps=['new','under_review','confirmed','artist_assigned','completed']; final labels=['جديد','مراجعة','مؤكد','خبيرة','مكتمل']; final index=steps.indexOf(current); return Wrap(spacing:6, runSpacing:6, children:List.generate(steps.length,(i){ final active = index >= i || (current=='in_progress' && i<=3); return Chip(label:Text(labels[i]), backgroundColor:active?const Color(0xFFD8B37A):const Color(0xFFF4EEE7)); })); } }
String statusArabic(dynamic status){ const labels={'new':'طلب جديد','under_review':'جاري المراجعة','waiting_customer_confirmation':'بانتظار تأكيد العميلة','confirmed':'تم تأكيد الحجز','artist_assigned':'تم تعيين خبيرة التجميل','in_progress':'قيد التنفيذ','completed':'مكتمل','cancelled':'ملغي','unavailable':'غير متوفر'}; return labels[status?.toString()] ?? status?.toString() ?? '-'; }
